version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.24.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-network

  chrome:
    image: selenium/node-chrome:4.24.0
    container_name: selenium-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444/grid/register
      - SE_NODE_VIDEO=true
    networks:
      - selenium-network
    volumes:
      - ./videos:/opt/selenium/videos  # Mount a local directory to store videos

  firefox:
    image: selenium/node-firefox:4.24.0
    container_name: selenium-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444/grid/register
      - SE_NODE_VIDEO=true
    networks:
      - selenium-network
    volumes:
      - ./videos:/opt/selenium/videos  # Mount a local directory to store videos

  edge:
    image: selenium/node-edge:4.24.0
    container_name: selenium-edge
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444/grid/register
      - SE_NODE_VIDEO=true
    networks:
      - selenium-network
    volumes:
      - ./videos:/opt/selenium/videos  # Mount a local directory to store videos

networks:
  selenium-network:
    driver: bridge